# Generated by Django 4.2.5 on 2023-09-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'diary',
            },
        ),
    ]
