# Generated by Django 4.2.5 on 2023-10-02 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='create_at',
        ),
    ]
