# Generated by Django 4.2.5 on 2023-10-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_diary_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='create_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
